spring.application.name=api-gateway-service

server.port=8000
#eureka config
eureka.client.service-url.defaultZoe=http://localhost:8761/eureka/

spring.cloud.gateway.discovery.locator.enabled=false
spring.cloud.netflix.eureka.discovery.enabled=true

#default static routes for product services application
spring.cloud.gateway.routes[0].id=product-services
spring.cloud.gateway.routes[0].=lb://PRODUCT-SERVICES
spring.cloud.gateway.routes[0].predicates[0]=Path=/products/**


#default static routes for product order application
spring.cloud.gateway.routes[1].id=order-services
spring.cloud.gateway.routes[1].=lb://ORDER-SERVICES
spring.cloud.gateway.routes[1].predicates[0]=Path=/orders/**